# Generated by Django 3.2.7 on 2021-09-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('category', models.CharField(max_length=200)),
                ('discount', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
