# Generated by Django 3.2.7 on 2021-09-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
