# Generated by Django 3.2.7 on 2021-09-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
