# Generated by Django 3.2.7 on 2021-09-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_auto_20210922_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.BigIntegerField(blank=True),
        ),
    ]
