# Generated by Django 3.2.7 on 2021-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_auto_20210922_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
