# Generated by Django 3.2.7 on 2021-09-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0010_alter_products_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(),
        ),
    ]
